[env:rumba32_f446ve]
platform = ststm32
board = rumba32_f446ve
framework = arduino
monitor_speed = 250000

board_upload.protocols = cmsis-dap
upload_protocol = cmsis-dap
lib_ldf_mode = deep+
lib_deps = SPI
