[env:fysetc_f6_13]
platform = atmelavr
board = fysetc_f6_13
framework = arduino
upload_port = COM4


lib_deps =
    microbahner/MobaTools @ ^2.5.0
    teemuatlut/TMCStepper @ ^0.7.3
    waspinator/AccelStepper @ ^1.64